export enum ApplicationStage {
  NEW = 'NEW',
  SCREENING = 'SCREENING',
  ASSESSMENT = 'ASSESSMENT',
  INTERVIEW = 'INTERVIEW',
  FEEDBACK_PENDING = 'FEEDBACK_PENDING',
  APPROVAL = 'APPROVAL',
  SELECTED = 'SELECTED',
  JOINING = 'JOINING',
  JOINED = 'JOINED',
}

export enum ApplicationOutcome {
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  ON_HOLD = 'ON_HOLD',
  REDIRECTED = 'REDIRECTED',
  CLOSED = 'CLOSED',
}
