export enum CandidateSourceType {
  MANUAL = 'MANUAL',
  CV_UPLOAD = 'CV_UPLOAD',
  SPREADSHEET = 'SPREADSHEET',
  JOB_PORTAL = 'JOB_PORTAL',
  REFERRAL = 'REFERRAL',
  INTERNAL_POOL = 'INTERNAL_POOL',
  EVENT = 'EVENT',
  HEADHUNTER = 'HEADHUNTER',
}
