export enum InterviewStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RESCHEDULED = 'RESCHEDULED',
}

export enum EvaluationRecommendation {
  STRONGLY_RECOMMEND = 'STRONGLY_RECOMMEND',
  RECOMMEND = 'RECOMMEND',
  NEUTRAL = 'NEUTRAL',
  DO_NOT_RECOMMEND = 'DO_NOT_RECOMMEND',
}
