export enum JoiningChecklistStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  READY = 'READY',
  COMPLETED = 'COMPLETED',
}

export enum JoiningItemStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum JoiningItemType {
  CANDIDATE_ACCEPTANCE = 'CANDIDATE_ACCEPTANCE',
  REQUIRED_DOCUMENTS = 'REQUIRED_DOCUMENTS',
  REFERENCE_CHECK = 'REFERENCE_CHECK',
  OFFER_LETTER = 'OFFER_LETTER',
  JOINING_DATE = 'JOINING_DATE',
  IT_REQUEST = 'IT_REQUEST',
  WORKSPACE = 'WORKSPACE',
  ID_CARD = 'ID_CARD',
  TRANSPORT = 'TRANSPORT',
  INDUCTION = 'INDUCTION',
  DEPARTMENT_NOTIFICATION = 'DEPARTMENT_NOTIFICATION',
  JOINING_COMPLETION = 'JOINING_COMPLETION',
  DEPARTMENTAL_HANDOVER = 'DEPARTMENTAL_HANDOVER',
}
