export enum MessageStatus {
  DRAFTED = 'DRAFTED',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  APPROVED = 'APPROVED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
}

export enum MessageChannel {
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
}

export enum MessageType {
  INTERVIEW_INVITATION = 'INTERVIEW_INVITATION',
  INTERVIEW_REMINDER = 'INTERVIEW_REMINDER',
  RESCHEDULE = 'RESCHEDULE',
  DOCUMENT_REQUEST = 'DOCUMENT_REQUEST',
  SELECTION = 'SELECTION',
  REJECTION = 'REJECTION',
  JOINING_REMINDER = 'JOINING_REMINDER',
}
