export enum SystemRole {
  TA_ADMIN = 'TA_ADMIN',
  RECRUITER = 'RECRUITER',
  DEPT_HEAD = 'DEPT_HEAD',
  HIRING_MANAGER = 'HIRING_MANAGER',
  PANEL_MEMBER = 'PANEL_MEMBER',
  HR_LEADERSHIP = 'HR_LEADERSHIP',
  AUDIT_USER = 'AUDIT_USER',
  TECH_ADMIN = 'TECH_ADMIN',
}
