export enum TaskStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
}

export enum TaskType {
  REVIEW_CANDIDATE = 'REVIEW_CANDIDATE',
  SCHEDULE_INTERVIEW = 'SCHEDULE_INTERVIEW',
  SUBMIT_EVALUATION = 'SUBMIT_EVALUATION',
  APPROVE_MESSAGE = 'APPROVE_MESSAGE',
  JOINING_ITEM = 'JOINING_ITEM',
  CUSTOM = 'CUSTOM',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}
